### ISSUE TITLE
dashboard project names could be confusing

### ISSUE THREAD

**Issue by ogrotten** [wistityhq/strapi#10]
There's currently nothing other than the project name to identify a project on the dashboard. This means that multiple projects with the same name could be easily confused. Clearly there's some identifier that keeps it straight in your system, perhaps that info could be revealed?

Suggestion: Perhaps you could identify it by something automated, tho there could be security concerns with possible identifiers (computer name, ip address, etc). It may even be as simple as forcing the user to use unique names.

**Comment by Aurelsicoko** [comment]
Each application connected with the Strapi Studio has a unique identifier. This identifier is available in the `config/global.json` file. We could display it before the project name ?

**Comment by loicsaintroch** [comment]
I like your suggestion @ogrotten: force the user to use unique names could be a great option.

**Comment by loicsaintroch** [comment]
I have a question about forcing users to use unique name. You think about a unique name like an identifier for every apps of every users juste like Heroku do? Or a unique app name by user?

**Comment by Aurelsicoko** [comment]
@loicsaintroch A unique name for every app of every user would mean that the CLI ```$ strapi new <appName>``` should return an error in case this name already exists.

**Comment by loicsaintroch** [comment]
Well yes, and no. Either the CLI returns an error when we create a new project or we based the identifier on the `name` defined in the `package.json` file. I think the second solution is way better, but not perfect.

There are some tricky use cases: no Internet access, Studio connection disabled, etc.

**Comment by Aurelsicoko** [comment]
I think our current solution is the best. We already have a unique identifier. In my opinion, this is an user experience problem, not a technical problem. 

We can't require an Internet access. If the Strapi Studio connection failed for many reasons, we have to create another CLI `$ strapi init` to identify this project with the Strapi Studio. This CLI will return and give an  identifier to this project. Moreover this CLI could be very interesting to change and get a new identifier for a project instead of create a new app with the existing CLI `$ strapi new <appName>`

**Comment by loicsaintroch** [comment]
Agreed.

**Comment by ogrotten** [comment]
It is a UX problem, to be sure.

I think a simple solution which doesn't change the current method at all would be to show the creation date on the dash right there with the project name. This doesn't require extra access as the date is on the package.json file. 

`strapi init` could also contain a number of commands for general maintenance of a project...  regenerating the secret key, renaming the proj, perhaps even more involved things like changing the database. Seems like feasibly an entire wing of the whole strapi project.

**Comment by Aurelsicoko** [comment]
I added the unique identifier next to the app name, and also the creation date to be sure there is no confusion. You will see those changes in the next release.

**Comment by loicsaintroch** [comment]
We'll definitely create a `$ strapi init` command for the next release.

Thank you @ogrotten!
