### ISSUE TITLE
token Attribute

### ISSUE THREAD

**Issue by PetrSnobelt** [wistityhq/strapi#100]
I try create model, with token attribute, but it don't work - it looks like it is reserved word...
Didn't work mean:
 - if it is required is imposible to create new item using admin
 - if I remove required attribute content of atribute is not stored
 - when I rename attribute and reload studio it works

Petr

**Comment by pierreburgy** [comment]
Hi @PetrSnobelt, did you create the attribute from the Studio or from the code (using a text editor)?
