### ISSUE TITLE
ManytoMany relations within same model

### ISSUE THREAD

**Issue by borantula** [wistityhq/strapi#105]
Does it possible to do relation between the entities of same model, like related articles or translation of kind of thing? I tried but it never saved that relation (via studio)

**Comment by pierreburgy** [comment]
Hi @borantula,

What are the name of the model you used and the name of the relation key?

**Comment by borantula** [comment]
Hi @pierreburgy,
I tried Article to Article connection. Relation key is translationOf

**Comment by pierreburgy** [comment]
Here is an example:

![screen shot 2016-04-21 at 10 41 31](https://cloud.githubusercontent.com/assets/5550462/14703014/e02135fe-07ad-11e6-8648-eaab73d0b818.png)
![screen shot 2016-04-21 at 10 42 17](https://cloud.githubusercontent.com/assets/5550462/14703016/e2fa0382-07ad-11e6-9e16-d39baa49ccb6.png)
![screen shot 2016-04-21 at 10 42 47](https://cloud.githubusercontent.com/assets/5550462/14703024/e86567d0-07ad-11e6-93fa-74565a7530bf.png)

Is what you are trying to do?

**Comment by borantula** [comment]
Thanks @pierreburgy  :) 

My mistake was naming both RELATION ATTRIBUTE and RELATION KEY IN ARTICLE as translationOf. When I changed relation attribute as **translations** it started working perfectly.

Maybe naming them same can be prevented within studio on manytomany relations.

**Comment by pierreburgy** [comment]
You are right @borantula, a warning message would me more than relevant here.
