### ISSUE TITLE
Strapi Studio is not sending emails / cannot login

### ISSUE THREAD

**Issue by samgranger** [wistityhq/strapi#110]
Tried to sign up with 2 email addresses. Both accounts are not receiving emails (outlook & gmail). Assuming I need to verify my account before I can login since I get a wrong email or password error when trying to login. Tried to reset password without success either.

**Comment by loicsaintroch** [comment]
Hey @samgranger. We encountered some issues due to Mandrill becoming a paid MailChimp add-on. Should be fixed now thanks to @lauriejim.

**Comment by samgranger** [comment]
I already had a suspicion, thanks for enabling my account!
