### ISSUE TITLE
"Application not connected" error in studio

### ISSUE THREAD

**Issue by markus138** [wistityhq/strapi#111]
Hello, have problems bootstrapping my application. I can create a new app and get to the point where I'd like to sync the app with the studio. I added the "secretKey" in `config/studio.json` and restartet my app, but I get following err on syncing:

```
  http://studio.strapi.io/socket/pull?appId=1978&token=<token>
  {
    status: "error",
    msg: "Application not connected"
  }
```

The only thing I did in my code was moving `config/environments/development` to `config/environments/dev`, because otherwise node didn't find the necessary json configs.

versions:
strapi 1.5.4, node 5.1.0, npm 3.5.4, os x

**Comment by Aurelsicoko** [comment]
Hi @markus138!

You can't move your code in `config/environments/dev`. For security reason, the Studio only works when the environment is called `development`. To fix your issue, try to undo your changes and move your configurations in `config/environments/development`.

I hope this will help you!

**Comment by markus138** [comment]
thanks, it works now with editing `npm start` to `NODE_ENV=development && node --harmony server.js`. otherwise I got an undefined error for `config/environments/dev`
