### ISSUE TITLE
Strapi studio cannot change password

### ISSUE THREAD

**Issue by sulemankm** [wistityhq/strapi#113]
Hi I've recently registered at strapi studio.  Tried to change my profile and password from the studio.  The password change operation failed for some reason.  Now I cannot login to the studio any more.

There is also no forgot password link on the studio login screen, so no way to automatically reset my password.

Plz reset my password or guide me how to reset / change my password.

**Comment by Aurelsicoko** [comment]
Hi @sulemankm!

We have some troubles with our mail server. We are based on Mandrill, but the service was shut down, two days ago. To resolve your issue quickly, I recommend you to go on our public [Slack](http://slack.strapi.io). One of the team core's member will discuss with you to fix your problem.

**Comment by sulemankm** [comment]
Thanks, I've joined the slack and raised the question over there as well.  Waiting still.
