### ISSUE TITLE
Missing config files for test environment

### ISSUE THREAD

**Issue by abelsoares** [wistityhq/strapi#117]
Have been adding test to an strapi app, i miss having env config files for testing purposes.
I added it myself, but it would be good if this can be handled by the strapi generator.  
I think the directory name which will match the env name should be called `test`.

**Comment by pierreburgy** [comment]
Good idea @abelsoares. Do you have time to submit a pull request for that? 

Also, we could add a generator `strapi generate env [staging]` which adds a `staging` folder in every config folders (`/config/environments` and `/api/[model]/config/environments`).

**Comment by abelsoares** [comment]
I'll open a PR to add the `test` config files.

**Comment by pierreburgy** [comment]
👍

**Comment by pierreburgy** [comment]
Added in #119.
