### ISSUE TITLE
Use Mongo from the start

### ISSUE THREAD

**Issue by jblok** [wistityhq/strapi#121]
Hi,

How do I start a strapi project so that even the default models (user, role and route) use the mongo connector instead of the permanent connection.

I tried to change the connection property in Route.settings.json to mongo, but when I started the server  I got an error in this file:

/usr/local/lib/node_modules/strapi/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/joinTables.js:224

I guess it's trying to run a migration to mongo? I am just starting out though, so I'm thinking if there is a way to just always use mongo by default from the start, I can avoid any migration.

Thanks! 💃

**Comment by pierreburgy** [comment]
Hi @jblok,

Actually, what you did should work. It looks like the problem is related to the adaptor.

Did you try to destroy the database before starting the server with the new configuration?

**Comment by pierreburgy** [comment]
Actually this is probably due to the models structure. So, please try one of these options to fix the problem: 

Solution 1: 
Use `default` connection for your model `Role` in `Role.settings.json`

Solution 2: 
Add `"dominant": true` to the `roles` attribute in `Route.settings.json`
```json
"roles": {
  "collection": "role",
  "via": "routes",
  "dominant": true
}
```
OR
Add `"dominant": true` to the `routes` attribute in `Role.settings.json`
```json
"routes": {
  "collection": "route",
  "via": "roles",
  "dominant": true
}
```

**Comment by jblok** [comment]
Hi @pierreburgy 

Thanks so much for your response. I hadn't set Role, and User settings to use mongo, so they were still using the default connection. Since Routes depends on Roles, I suspect this might have been the issue. All good now, by using the mongo connection everywhere.

I might have a go at editing the CLI to define a database system from the start (one day!) :)

**Comment by pierreburgy** [comment]
Hi @jblok,

Yes, but instead of the CLI, you can also use the [Studio](http://studio.strapi.io/) to make these changes.
