### ISSUE TITLE
when will v2 release?

### ISSUE THREAD

**Issue by sskyy** [wistityhq/strapi#124]
I'm a fan of strapi, this project helped me speed up my project development. When will v2 release?

**Comment by lauriejim** [comment]
Hello @sskyy ! Happy to see you on Strapi.

About the v2 we made a blog post to explain what are next steps of Strapi - http://strapi.io/blog/the-future-of-strapi
You will find more information about the Strapi v2.

**Comment by zdhz** [comment]
Updated URL - https://blog.strapi.io/the-future-of-strapi/

May be worth setting up a 301 redirect :)
