### ISSUE TITLE
Polymorphic relations and custom fields in many-to-many in v2

### ISSUE THREAD

**Issue by jakobrosenberg** [wistityhq/strapi#125]
Is this something you've considered for v2?

For instance, it would make it possible to create a user role table with the structure shown below.

```
user_id: 4
role: "editor"
foreign_table: "articles"
foreign_id: "23"
```

**Comment by pierreburgy** [comment]
Hi @jakobrosenberg,

This is not implemented yet. We can do it at the framework level, but this feature make migrations more complicated.

**Comment by Aurelsicoko** [comment]
Thanks for having highlighted this issue. This is not our purpose to handle polymorphic relations at this time. I close this issue because this is not in our roadmap for the next months.
