### ISSUE TITLE
Strapi Login Errors

### ISSUE THREAD

**Issue by Gegham** [wistityhq/strapi#128]
I'm getting  these errors when trying to start app, how to avoid these errors ?

info: Server started in /Users/geghamharutyunyan/way4app/Our products/Web/StrapiAPI
info: Your server is running at http://localhost:1337
info: Your admin panel is available at http://localhost:1337/admin/
debug: Time: Wed Jun 08 2016 18:34:17 GMT+0400 (AMT)
debug: Environment: development
debug: Process PID: 5464
debug: Cluster: master
info: To shut down your server, press <CTRL> + C at any time

error:  TypeError: Promise.defer is not a function
    at Object.exports.create (/Users/geghamharutyunyan/way4app/Our products/Web/StrapiAPI/api/user/config/fixtures/route.js:18:28)
    at /Users/geghamharutyunyan/way4app/Our products/Web/StrapiAPI/config/functions/bootstrap.js:16:29
error: Bootstrap encountered an error.
error:  TypeError: Promise.defer is not a function
    at Object.exports.create (/Users/geghamharutyunyan/way4app/Our products/Web/StrapiAPI/api/user/config/fixtures/route.js:18:28)
    at /Users/geghamharutyunyan/way4app/Our products/Web/StrapiAPI/config/functions/bootstrap.js:16:29

**Comment by pierreburgy** [comment]
What is your Node version?

**Comment by Gegham** [comment]
v6.2.1

**Comment by pierreburgy** [comment]
Strapi v1.x.x is not compatible with Node v6 yet. Please switch to node v5 or less.

**Comment by Gegham** [comment]
Ok, thank again! @pierreburgy

**Comment by pierreburgy** [comment]
You are welcome

**Comment by ugommirikwe** [comment]
Hi. So I have other NodeJS frameworks and apps running on my machine that require Node v6.2.1; I reckon this would mean abandoning Strapi then. Or do you provide early access to download Strapi 2.0?
