### ISSUE TITLE
clone or migrate existing project

### ISSUE THREAD

**Issue by portokallidis** [wistityhq/strapi#129]
First of all , you deserve a BIG thanks and congratz for the strapi project! you 've done really well.
Now to the chase: 
I have started experimenting on cloud9 with strapi and i am facing some issues on ports (C9 blocks all ports except 8080,8081,8082).
I have designed my api but the admin wont start probably due to port filtering or the proxy that sits in front of cloud9 domain.
So i want to move the configuration in another machine. Can i just git add . to a repository and clone it elsewhere or just copy the folder?

**Comment by pierreburgy** [comment]
Thank you @portokallidis.

If you need to change the port of you server, please edit the `/config/environments/production/server.json` file and add the following lines:

```
{
   "port": 8080,
   "host": "yourdomain.com"
   ...
}
```

**Comment by portokallidis** [comment]
Hi Perre, 
Yes i saw that but the problem is that internally the service is deployed as localhost:8080 and externally it comes out like this strapi-portokallidis.c9users.io.
So a proxy server setup would be definately useful.
I think you have an option for enabling a proxy server but i didnt manage to configure it properly.
But this is another issue.
I opened this issue because i wanted to know if i could copy my strapi-app to another dev machine? and how can i do it?

**Comment by pierreburgy** [comment]
Hi @portokallidis,
So, yes, you can use `git add .`, etc. and, then, clone it (do not forget to run `npm install` inside the project folder).
