### ISSUE TITLE
Support JSON API

### ISSUE THREAD

**Issue by kaermorchen** [wistityhq/strapi#13]
Hello.

Do you plan to add support [JSON API](http://jsonapi.org)? Support JSON API important Ember.js developers and other frameworks.

**Comment by loicsaintroch** [comment]
Hey @kaermorchen.

Good question. We'll definitely support JSON API. I know a lot of developers ask for this support especially Ember developers you're right.

Maybe this is something we can plan for the `v1.3.0`.
Are you familiar with this? If so, do you want to help us on it?

**Comment by kaermorchen** [comment]
I think I can try help with it.

**Comment by loicsaintroch** [comment]
Awesome thank you! Feel free to join us on Slack to talk about it: http://strapi.io/support

**Comment by loicsaintroch** [comment]
Hey @kaermorchen, it's been a while since your last message. We are going to release the v1.4.0 in a few minutes so we'll support JSON API when you'll be ready. Please keep in touch.

**Comment by kaermorchen** [comment]
I'm sorry, at the moment I don't work with strapi. I was not able to work with studio on my system (windows 7 x64). And I switched to work with loopback.

**Comment by loicsaintroch** [comment]
Hey @kaermorchen, is your issue related to #29? If so, can you please help us?
Have you tried with `strapi@1.4.0`?

```bash
$ npm uninstall strapi -g
$ npm cache clean
$ npm install strapi -g
$ strapi new myApp
$ cd myApp
$ strapi start
```

**Comment by loicsaintroch** [comment]
@kaermorchen: I'm closing this issue since we unfortunately don't have any news from you... Also, we'll support the JSON API specification in the v2.0.0 as you can see on the [roadmap](https://github.com/wistityhq/strapi/blob/master/ROADMAP.md).
