### ISSUE TITLE
generated example app

### ISSUE THREAD

**Issue by portokallidis** [wistityhq/strapi#131]
I hope i am not spamming.
It would be a nice attraction for newcomers if there was an example app/api generated by strapi in a repository deployed to heroku/or elsewhere

**Comment by pierreburgy** [comment]
Good idea @portokallidis, we plan to fill this Github organisation with examples and tutorials from us and from the community: https://github.com/strapi-101

In the meantime, feel free to look for examples in Github: https://github.com/search?utf8=%E2%9C%93&q=strapi

**Comment by Aurelsicoko** [comment]
Good idea! As @pierreburgy has already said, we created a specific repository for this. We will push in it a `strapi-starter-kit` and a more complex app built with Strapi. Feel free to submit your app if you have already done a project, this could be awesome for the community!
