### ISSUE TITLE
Support node v6

### ISSUE THREAD

**Issue by jamesjwarren** [wistityhq/strapi#132]
When running the default generated app on node v6.2.1 I get the following error:
```
error:  TypeError: Promise.defer is not a function
    at Object.exports.create (.../api/user/config/fixtures/route.js:18:28)
    at .../config/functions/bootstrap.js:16:29
error: Bootstrap encountered an error.
error:  TypeError: Promise.defer is not a function
    at Object.exports.create (.../api/user/config/fixtures/route.js:18:28)
    at .../config/functions/bootstrap.js:16:29
```

**Comment by pierreburgy** [comment]
Hi @jamesjwarren,

Node v6 is not supported yet by Strapi v1, but it will be by Strapi v2. In the meantime, please use Node v5.

**Comment by ugommirikwe** [comment]
Hi. So I have other NodeJS frameworks and apps running on my machine that require Node v6.2.1; I reckon this would mean abandoning Strapi then. Quite a pity -- I was trying out the framework now to see if I should build on it now not next week or next month.

Or do you provide early access to download Strapi 2.0?

Thanks.

**Comment by pierreburgy** [comment]
Hi @ugommirikwe, here is a Gist to install Strapi v2: https://gist.github.com/pierreburgy/6ff3ad7833747db00a2317e1f95b85bb

But as you can see here: https://github.com/wistityhq/strapi/issues/126, this version is not stable.

**Comment by dj-hedgehog** [comment]
@ugommirikwe Have you thought about using `nvm`? It makes managing your Node versions a breeze.

**Comment by ugommirikwe** [comment]
@dj-hedgehog I haven't used `nvm` before; I'll check it out now.

**Comment by FabioSilvaBRZ** [comment]
NVM + Strapi = success... of course, if your app is compatible with node V5

**Comment by pierreburgy** [comment]
@jamesjwarren @ugommirikwe @dj-hedgehog @FabioSilvaBRZ  Strapi v1 is now compatible with every Node versions, including 7.x. Feel free to upgrade: `npm i strapi -g`. More information here: http://blog.strapi.io/release-v1-6.
