### ISSUE TITLE
Strapi doesn't load production configuration

### ISSUE THREAD

**Issue by dj-hedgehog** [wistityhq/strapi#134]
I'm using the latest code of the v2 branch. 
When using: `NODE_ENV=production && strapi start` it loads the configuration from `config/environments/development` instead of `config/environments/production`.
Can you verify this problem, please?

As a workaround I created another database-connection which I am loading.

**Comment by Aurelsicoko** [comment]
Try to update your package.json like below and run `npm start`. It should work!

```
...
"scripts": {
    "start": "NODE_ENV=production node server.js"
 }
...
```

**Comment by franzos** [comment]
I have the same issue. I cant get strapi to run in production mode.
`NODE_ENV=production && strapi start` - development
`npm start` - development
changes in package.json - still development

`npm@5.5.1, strapi@3.0.0-alpha.7.3, node@v9.3.0`

**Comment by Aurelsicoko** [comment]
@franzos You need to remove the `&&` in your command `NODE_ENV=production strapi start`

**Comment by AnorakTech** [comment]
Same behavior here. strapi won't start in production environment.

`
{
  "name": "workflow",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application.",
  "main": "./server.js",
  "scripts": {
    "setup": "npm install --ignore-scripts && cd admin && npm run setup",
    "start": "NODE_ENV=production node server.js",
    "strapi": "node_modules/strapi/bin/strapi.js",
    "lint": "node_modules/.bin/eslint api/**/*.js config/**/*.js plugins/**/*.js",
    "postinstall": "node node_modules/strapi/lib/utils/post-install.js"
  },
  "devDependencies": {
    "babel-eslint": "^7.1.1",
    "eslint": "^3.12.2",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-react": "^6.8.0"
  },
  "dependencies": {
    "lodash": "4.x.x",
    "mongoose": "^4.13.9",
    "strapi": "3.0.0-alpha.7.3",
    "strapi-mongoose": "3.0.0-alpha.7.3"
  },
  "author": {
    "name": "A Strapi developer",
    "email": "",
    "url": ""
  },
  "maintainers": [
    {
      "name": "A Strapi developer",
      "email": "",
      "url": ""
    }
  ],
  "strapi": {
    "uuid": "3e10a881-ebf5-4530-a13d-c46c8a3f29f5"
  },
  "engines": {
    "node": ">= 7.0.0",
    "npm": ">= 3.0.0"
  },
  "license": "MIT"
}

`


`
INFO (9960 on 10.10.11.2): Server started in C:\Users\ATAC\Desktop\strapi\workflow
INFO (9960 on 10.10.11.2): Your server is running at http://localhost:1336
DEBUG (9960 on 10.10.11.2): Time: Tue Jan 16 2018 10:37:11 GMT+0100 (Vest-Europa (normaltid))
DEBUG (9960 on 10.10.11.2): Launched in: 1260 ms
DEBUG (9960 on 10.10.11.2): Environment: development
DEBUG (9960 on 10.10.11.2): Process PID: 9960
DEBUG (9960 on 10.10.11.2): Version: 3.0.0-alpha.7.3 (node v9.4.0)
INFO (9960 on 10.10.11.2): To shut down your server, press <CTRL> + C at any time
`

**Comment by Aurelsicoko** [comment]
@AnorakTech Did you try to run this command `NODE_ENV=production npm start`?

I tested it again and it works as expected.
