### ISSUE TITLE
Model attributes customization inside admin panel

### ISSUE THREAD

**Issue by peresleguine** [wistityhq/strapi#136]
I tried to follow [the docs](http://strapi.io/documentation/admin#customization) but I couldn't figure out how to properly customize admin panel – manage attributes visibility per action, set default values in form fields, etc.

Suppose I've generated `Project` API with `name`, `isActive` and `slug` attributes via the CLI. I want to: 

- hide slug from `new` and `edit` actions and use `beforeCreate` callback to generate it behind the scenes
- set `isActive` to true by default (here I mean form input, not db settings)

JSON settings seems better than overriding view templates.

[Related question on stackoverflow](http://stackoverflow.com/questions/38015876/model-attributes-visibility-inside-admin-panel)

**Comment by pierreburgy** [comment]
Hi @peresleguine,

Thanks for this issue. I replied directly through stackoverflow.
