### ISSUE TITLE
Documentation: Logging in

### ISSUE THREAD

**Issue by gregbenner** [wistityhq/strapi#15]
Would be great to show an example of logging a user in from the public site. I see the admin section has a full fledged angular application and 1000's of lines of code to do this. It's still not clear the mechanism to create a session.

Is it simply a POST to /login with a response that should be added as cookie?

**Comment by pierreburgy** [comment]
What do you mean by public site ? 

Here is the documentation for users authentification : http://strapi.io/documentation/users

**Comment by gregbenner** [comment]
Using POST /auth/local/register I get back the newly created user and jwt.
Using POST /auth/local/login with the same users filled in credentials:
{
  "identifier": "contact@company.com",
  "password": "123456"
}
I get back a 400: 
http://localhost:1337/auth/local/login Failed to load resource: the server responded with a status of 400 (Bad Request)

**Comment by gregbenner** [comment]
By public site I mean, not the admin section.. The project root index.html.

<script>
    $.ajax({
      type: "POST",
      url: '/auth/local/register',
      data: {
        username: "bobbybrown123",
        email: "bobbybrown123@gmail.com",
        password: "bobbybrown123"
      },
      success: function(response) {
        console.log(response) // works returns user
      }
    });
   
  // executed after user is created, 400 response
    $.ajax({
      type: "POST",
      url: '/auth/local/login',
      data: {
        identifier: "bobbybrown123@gmail.com",
        password: "bobbybrown123"
      },
      success: function(response) {
        console.log(response)
      }
    });
    </script>

**Comment by gregbenner** [comment]
Ok I've figured it out. The documentation http://strapi.io/documentation/users#local-login says */auth/local/login* but when I viewed the network request of logging in from admin it is actually **/auth/local**
Maybe it's an error in the documentation?

**Comment by pierreburgy** [comment]
Good catch, @sylvainlap just made a pull request to update the documentation : https://github.com/wistityhq/strapi-docs/pull/2
Thanks @gregbenner @sylvainlap
