### ISSUE TITLE
Dashboard PUT method

### ISSUE THREAD

**Issue by gregbenner** [wistityhq/strapi#18]
Looks like PUT in dashboard is disallowed on everything.

Request URL:http://localhost:1337/dashboard/explorer/user/2
Request Method:PUT
Status Code:405 Method Not Allowed

**Comment by pierreburgy** [comment]
That's weird, we're gonna check that asap.

**Comment by pierreburgy** [comment]
Thanks for your feedback. It's now fixed: https://github.com/wistityhq/strapi/pull/19
