### ISSUE TITLE
Models dont save or update?

### ISSUE THREAD

**Issue by GeoffreyEmery** [wistityhq/strapi#29]
I just created a sample app and connected it to the dashboard. The models dont seem to update and i can't create a new model .  the save bar never quit gets to the end. When i use the cli it works and sync but then can't update a atribute via the dashboard.

**Comment by Aurelsicoko** [comment]
Hi @GeoffreyEmery, thank you for your feedback!

[Did you take a look at the F.A.Q. ?](http://strapi.io/faq). We have a specific question concerning your behavior.

However in your case, I think this is writing permission issues in your project. Can you change the writing permissions to 777 in your application directory and tell me if it works?

**Comment by GeoffreyEmery** [comment]
<img width="501" alt="strapi" src="https://cloud.githubusercontent.com/assets/3301804/11119416/4e9db702-88fe-11e5-9f42-dc091406e21d.png">

**Comment by Aurelsicoko** [comment]
Are you using Linux? And can you show me your logs when the server is started?

**Comment by GeoffreyEmery** [comment]
windows - other questions attached

<img width="501" alt="2015-11-12_13-05-10" src="https://cloud.githubusercontent.com/assets/3301804/11131157/11112ac8-893e-11e5-8e26-7351ef350bb0.png">

**Comment by GeoffreyEmery** [comment]
https://drive.google.com/file/d/0B49J0ZEldyQaWmpjY3YtN0E5Q00/view?usp=sharing
video

**Comment by Aurelsicoko** [comment]
Thanks for the video! We will release some updates on the Studio and the framework very soon! I hope this will fix your issue. Which version of Strapi are you using ($ strapi -v)? Can you also take a screenshot of your browser console? I don't know yet where the bug comes from but we will find it :)

**Comment by loicsaintroch** [comment]
Hey @GeoffreyEmery, do you still have this issue with `strapi@1.4.0` released 3 days ago? Here are some simple steps to test:

```bash
$ npm uninstall strapi -g
$ npm cache clean
$ npm install strapi -g
$ strapi new myApp
$ cd myApp
$ strapi start
```

**Comment by loicsaintroch** [comment]
Closing this issue since we don't have any news...
