### ISSUE TITLE
Don't allow creating api's which don't match the pattern

### ISSUE THREAD

**Issue by dj-hedgehog** [wistityhq/strapi#35]
I created an api called `ali-api`. After starting the strapi-server I'm greated by the error below.
The name should be checked at creation time.
Do you want me to  make a PR to add this check to https://github.com/wistityhq/strapi-generate-api?

```
ali-api $ strapi generate api ali-api
info: Generated a new api `ali-api` at `./api`.
ali-api $ strapi start
info: Your server is running at http://localhost:1337
debug: Time: Fri Nov 20 2015 10:06:59 GMT+0100 (CET)
debug: Environment: development
debug: Process PID: 12479
debug: Cluster: master
info: To shut down your server, press <CTRL> + C at any time

Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "Ali-api" does not.
```

**Comment by loicsaintroch** [comment]
Hey @dj-hedgehog! Good catch. Thanks a lot for your feedback.
We'd be glad to merge a PR, definitely yes! :-)

**Comment by dj-hedgehog** [comment]
Cool, it will take me a few days though as I'm drowning in work right now :)

**Comment by loicsaintroch** [comment]
Sure no worries. Thanks a lot @dj-hedgehog.

**Comment by dj-hedgehog** [comment]
I couldn't wait :)
https://github.com/wistityhq/strapi-generate-api/pull/1

**Comment by loicsaintroch** [comment]
Awesome, fixed! Thank you for your feedback @dj-hedgehog.
