### ISSUE TITLE
`strapi generate api` without further arguments leads to error

### ISSUE THREAD

**Issue by dj-hedgehog** [wistityhq/strapi#36]
Well this one is pretty easy but i'll hand to yourself how you want to fix it.

This code is from https://github.com/wistityhq/strapi-generate-api/blob/master/lib/before.js
When executing `strapi generate api` pluralize doesn't handle the `undefined` gracefully so we have to do it ourself.

````
TypeError: Cannot read property 'toLowerCase' of undefined
```

```
  // `scope.args` are the raw command line arguments.
  _.defaults(scope, {
    id: scope.args[0],
    idPluralized: pluralize.plural(scope.args[0]),
    attributes: _.slice(scope.args, 1)
  });

  // Validate custom scope variables which are required by this generator.
  if (!scope.rootPath || !scope.id) {
    return cb.invalid('Usage: `$ strapi generate api <myAPI> [attribute|attribute:type ...]`');
  }
```

**Comment by loicsaintroch** [comment]
Interesting, thank you @dj-hedgehog I'll take a look at it in the next few days.

**Comment by loicsaintroch** [comment]
Hey @dj-hedgehog, just fixed this issue on the `strapi-generate-api` repository: https://github.com/wistityhq/strapi-generate-api/commit/4817b3d87107a66c716928f83ca9c2b0b8fad9a0.

Thank you for your help.
