### ISSUE TITLE
Uploading Files Thru Admin

### ISSUE THREAD

**Issue by aaronksaunders** [wistityhq/strapi#38]
am I missing something or is it not implemented yet? Also is there an actual working link to the documentation?

**Comment by loicsaintroch** [comment]
Hi @aaronksaunders, this feature is not implemented in the front-end yet, only the API is. The good news is we are going to open-source the dashboard in the next few days so anyone will be able to contribute and add this feature.

Regarding the documentation it was a server error during the compilation of the documentation. It happened a few hours ago. It's now fixed. Thank you for your help. ;-)
