### ISSUE TITLE
grant package

### ISSUE THREAD

**Issue by gregbenner** [wistityhq/strapi#40]
/home/ubuntu/workspace/node_modules/strapi/node_modules/grant-koa/node_modules/grant/node_modules/request/node_modules/bl/node_modules/readable-stream/lib/_stream_duplex.js:35
var keys = objectKeys(Writable.prototype);
           ^
TypeError: Cannot convert undefined or null to object

Clean install of Strapi 1.4.1.. after creating one user successfully then restarting the server I was bombarded with some missing packages I manually installed like 'is-array' then above is the output.

**Comment by pierreburgy** [comment]
hi @gregbenner, which version of node and npm are you using ?
