### ISSUE TITLE
Changing API prefix, admin not working anymore

### ISSUE THREAD

**Issue by senikk** [wistityhq/strapi#51]
When changing API prefix from Studio to "/api" and then restarting the server http://localhost:1337/admin/ doesn't work anymore because some code still is without the new API prefix.

Failing with these 404 in console:
```
http://localhost:1337/admin/config Failed to load resource: the server responded with a status of 404 (Not Found) 
http://localhost:1337/auth/logout Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by pierreburgy** [comment]
Good catch @senikk, we're gonna work on it asap.

**Comment by pierreburgy** [comment]
@senikk, here is what we are about to validate : https://github.com/wistityhq/strapi-generate-admin/commit/297b7eaf7278cb97fedf142b4dcea2259da7d1e7

What do you think about this solution ? (you juste have to launch `gulp dist` in the `/api/admin/public` folder)
