### ISSUE TITLE
 improve documentation site

### ISSUE THREAD

**Issue by kulakowka** [wistityhq/strapi#52]
The big problem - it's outdated documentation. Please specify the version of the library in the documentation? This will allow access to the documentation of older versions. This makes it easy to identify outdated documentation.

**Comment by loicsaintroch** [comment]
Hey @kulakowka, thanks for your feedback regarding versioning and documentation. To fix this problem we are going to put docs and code in the same repository (this one) so you'll be able to checkout the documentation for a specific version. This will happen next week. :-)
