### ISSUE TITLE
delete template from studio

### ISSUE THREAD

**Issue by senikk** [wistityhq/strapi#53]
Results in an empty warning message in studio and need to restart the server and refresh studio.

**Comment by Aurelsicoko** [comment]
@senikk Which version of Strapi do you have on your machine? Thanks for your feedback, I will take a look asap ;)

**Comment by senikk** [comment]
1.5.1

**Comment by Aurelsicoko** [comment]
Sorry for the delay! We solved this issue. You will be able to see this for the next release of the Studio (~2-3 weeks)
