### ISSUE TITLE
Unique way to create, update etc

### ISSUE THREAD

**Issue by SkinyMonkey** [wistityhq/strapi#57]
It's possible to do CRUD operations through query and body parameters.

Why allow two way of doing this? When is it useful to do it through queries?

**Comment by loicsaintroch** [comment]
Hey @SkinyMonkey, sorry for the lack of communication this last few weeks-- but this was for a good reason. I have some interesting news regarding this issue. We decided to remove built-in blueprints inside the framework itself and to put the logic inside controllers and services for each API. This way, you'll be able to make operations through whatever you need. This feature will be available when we'll release the v2.0.0. Thanks a lot for your feedback, it helped a lot for this decision. :-)
