### ISSUE TITLE
Error installing sails-mongo on Windows 8.1

### ISSUE THREAD

**Issue by zorobabel** [wistityhq/strapi#59]
I was trying to use the MongoDB adapter but the installation process failed. I know there are #7 , #11, #47 issues but I think the problem root is Windows + Strapi.

I've got similar error messages in cmd running:

`npm install sails-mongo --save`

What did I? Easy, I deleted the **__node_modules/__** folder and executed:

`npm install`
`npm install sails-mongo --save`

Problem kaput!

PD: I am using the Strapi's latest version (1.5.1).

**Comment by zorobabel** [comment]
@loicsaintroch, when you do `strapi new myapp`, inside of node_modules folder there are just "symbolic links", not real folders (I think Windows has a poor implementation of them):

![fur](https://cloud.githubusercontent.com/assets/12666007/12089002/3a2ad9f6-b2ae-11e5-9213-4a654c1b5df2.png)

But after doing my "solution", node_modules looks different and It works:

![mop](https://cloud.githubusercontent.com/assets/12666007/12089014/4f9344f4-b2ae-11e5-9483-b05714d81712.png)

**Comment by loicsaintroch** [comment]
@zorobabel Yes this behavior is normal. The generator `new` makes a symlink aiming to not copy every node modules. This is faster than copy and paste or even install them from npm.

**Comment by zorobabel** [comment]
@loicsaintroch, thanks, this is true but It was the problem

**Comment by loicsaintroch** [comment]
Yes definitely, still a problem.

**Comment by Karnith** [comment]
Issue is the same on Mac. I can't install any modules until I delete the node_modules folder and dother nap install...

**Comment by kulakowka** [comment]
I also encountered this problem. 
I deleted a folder `node_modules` and problem was solved.

**Comment by jakobrosenberg** [comment]
I just struggled with this one as well.

**Comment by loicsaintroch** [comment]
npm >= v3.0.0 no longer supports symbolic links in the `node_modules` directory. We'll work on a speedier solution to optimize `$ strapi new` that will be released in the v2. But in the mean time, your new Strapi app's dependencies must be set up using the classic `$ npm install` process.

**Comment by zorobabel** [comment]
@loicsaintroch Great, thanks!

**Comment by loicsaintroch** [comment]
This is now fixed and will be released for the v2. We simply copy/paste every dependency from the `node_modules` directory of the global installation to the local one. This is the best work around we've found.

Thank you all for your feedback, we appreciate.
