### ISSUE TITLE
Documentation is difficult to read

### ISSUE THREAD

**Issue by ogrotten** [wistityhq/strapi#6]
The ultralight font in a slightly small size on white background makes the docs difficult to read. I would suggest normal font weight (currently set to 300, 500 is normal) and a bit darker color (currently #777, would suggest #444). You might even consider a slight background color like #f4f4f4.

**Comment by Aurelsicoko** [comment]
Thank you for your feedback @ogrotten! We should increase the font size to 18px and apply a darker color like you suggest #444. We will test this new CSS style soon.

**Comment by ogrotten** [comment]
That would help, yes. However, the main readability problem isn't the font size, it's the font weight of 300.

**Comment by Aurelsicoko** [comment]
I've made some minors changes:
* Increased font weight to 400
* Increased line height to 24px instead of 20px
* Changed text color to #666666 instead of #777777
* Changed background color #f9f9f9 instead of #fff

**Comment by ogrotten** [comment]
I think it's beautiful! Much more readable.

**Comment by loicsaintroch** [comment]
Awesome! Thanks for your feedback @ogrotten, very useful.
