### ISSUE TITLE
Is this project dying?

### ISSUE THREAD

**Issue by hguillermo** [wistityhq/strapi#60]
I didn't see commits for many days. Are you still working actively?

**Comment by loicsaintroch** [comment]
Hey @hguillermo. Hell no this project is not dying at all! It was holidays and we were just enjoying some free time. We are working hard on the new version of the Strapi Studio and the second version of the framework. This is just the beginning!

**Comment by hguillermo** [comment]
Great to know that. I tried it and I liked it. I was just making sure if you guys are still developing things.

**Comment by loicsaintroch** [comment]
Awesome! Feel free to join [our active community on Slack](http://slack.strapi.io/) for more information.
