### ISSUE TITLE
Setting API route prefix breaks admin

### ISSUE THREAD

**Issue by buffonomics** [wistityhq/strapi#68]
When an API prefix is set, the admin interface breaks as the API routes it references also needs to change to accomodate the prefix.

i.e.
With prefix => /my/prefix,
/admin/config => 404 which the admin dashboard seems to be referencing directly regardless of set prefix.

Admin dashboard should use /my/prefix/admin/config => 200 OR there should be an "API prefix exclusion" feature where we define which APIs should/should not be affected by prefix.

**Comment by pierreburgy** [comment]
Hi @buffonomics,

Simply go in the `/api/admin/public` folder and run `npm install && gulp dist` (may be working only with Node 4). Then reload the admin page and it will work.

**Comment by loicsaintroch** [comment]
Related to #51.

**Comment by buffonomics** [comment]
Now admin doesn't launch.
I get blank screen with this in JS console:

Uncaught Error: [$injector:modulerr] Failed to instantiate module frontend due to:
Error: [$injector:unpr] Unknown provider: $tooltipProvider
http://errors.angularjs.org/1.4.8/$injector/unpr?p0=%24tooltipProvider
    at http://localhost:1337/admin/vendors.min.js:1:381
    at http://localhost:1337/admin/vendors.min.js:1:20014
    at r (http://localhost:1337/admin/vendors.min.js:1:19184)
    at Object.i [as invoke] (http://localhost:1337/admin/vendors.min.js:1:19521)
    at r (http://localhost:1337/admin/vendors.min.js:1:18572)
    at http://localhost:1337/admin/vendors.min.js:1:18696
    at o (http://localhost:1337/admin/vendors.min.js:1:807)
    at f (http://localhost:1337/admin/vendors.min.js:1:18473)
    at et (http://localhost:1337/admin/vendors.min.js:1:20163)
    at l (http://localhost:1337/admin/vendors.min.js:1:7506)
http://errors.angularjs.org/1.4.8/$injector/modulerr?p0=frontend&p1=Error%3…t%20l%20(http%3A%2F%2Flocalhost%3A1337%2Fadmin%2Fvendors.min.js%3A1%3A7506)

**Comment by buffonomics** [comment]
Using Node v4.2.4

**Comment by pierreburgy** [comment]
Could you try to run : 
 - `npm update strapi -g`
 - `rm -rf api/admin`
 - `strapi generate admin`
 - `cd api/admin/public`
 - `npm install`
 - `gulp dist`

**Comment by buffonomics** [comment]
Okay thanks that did it. Prefix now properly representing.

As an addition to that instruction, I also had to run:
`rm -rf public/admin` 
from the project root after step 2 before running:
`strapi generate admin`
to avoid the "symlink already exists" error.

**Comment by pierreburgy** [comment]
Good catch ;)
