### ISSUE TITLE
Feature request: Add select action to blueprint actions for find

### ISSUE THREAD

**Issue by stijlfigurant** [wistityhq/strapi#69]
riight now 'where', 'limit', 'skip' and 'sort' are actions used in the [blueprint actions](https://github.com/wistityhq/strapi/blob/master/lib/configuration/hooks/blueprints/actions/find.js#L26); 'select' would be a helpful one as well

**Comment by loicsaintroch** [comment]
Done and merged with #82 by @Aurelsicoko. Thanks for the suggestion @stijlfigurant. It will be released in the next patch. ;-)
