### ISSUE TITLE
changing to mongodb storage using the dashboard fails on install of the adapter.

### ISSUE THREAD

**Issue by ogrotten** [wistityhq/strapi#7]
Used the dashboard to setup the db. Sync to the local install did the following
```
debug: Rebuilding application dictionary...
debug: Reloading the ORM...
error: The adapter `sails-mongo` is not installed.
error: Execute `$ npm install sails-mongo --save` to install it.
vagrant:~/nodeprojs/strapi/blogg$ strapi start
error: The adapter `sails-mongo` is not installed.
error: Execute `$ npm install sails-mongo --save` to install it.
```

Issuing the command manually did the following:
```
vagrant:~/nodeprojs/strapi/blogg$ npm i sails-mongo --save
-
> kerberos@0.0.15 install /home/vagrant/nodeprojs/strapi/blogg/node_modules/sails-mongo/node_modules/mongodb/node_m
odules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory `/home/vagrant/nodeprojs/strapi/blogg/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory `/home/vagrant/nodeprojs/strapi/blogg/node_modules/sails-mongo/node_modules/mongodb/node_m$
dules/mongodb-core/node_modules/kerberos/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:$
3)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-52-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/nodeprojs/strapi/blogg/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongo$
b-core/node_modules/kerberos
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
sails-mongo@0.11.4 node_modules/sails-mongo
├── waterline-errors@0.10.1
├── waterline-cursor@0.0.6 (async@0.9.2, lodash@2.4.2)
└── mongodb@2.0.45 (readable-stream@1.0.31, es6-promise@2.1.1, mongodb-core@1.2.14)
```

The app started again, but I obviously am not confident that it will work, nor am I confident on return to default disk state. 

I don't remember, but I have a sense that I had a problem with installation of sails-mongo when experimenting with sails/waterline.

Suggestions:
* in the dashboard, database section, have the default 2 entries either be permanent, unchangeable and undeletable, or add a button that will "create default database" entries.
* allow access to those areas while not synced and queue the changes for the next sync. If I was unable to fix the problem with the database, and the local server wouldn't start, I wouldn't be able to delete or change the db option.

**Comment by loicsaintroch** [comment]
If I understand correctly, the `sails-mongo` fails to install, right? I like your second suggestion though. We'll think about it. Thanks!

About the adapters installation, it was on our roadmap, I will work on it tomorrow.

**Comment by ogrotten** [comment]
Yes it appeared that sails-mongo could not be installed 2nd hand by strapi.

IIRC, when I was originally experiementing with sails/sails-mongo, I had a stop at kerberos during compile.

**Comment by loicsaintroch** [comment]
We just made the auto install for adapters today. It will be published tomorrow for the v1.1.0.

But it's strange you have an issue during the installation of `sails-mongo`. It looks like its because of `node-gyp`. Did you try with Node.js v0.12.7 or Node.js v4.1.2?

**Comment by ogrotten** [comment]
i'm using 12.5

*(side note: `node-gyp` is the bane of my existance because it's consistently in the way during installations. It's the main thing that keeps me from setting up on windows as it wants to compile on install, and there's no such thing as a windows 'build-essential')*

**Comment by loicsaintroch** [comment]
Are you on OS X?

**Comment by loicsaintroch** [comment]
This is a common issue due to `node-gyp` and `bson` compatibilities for almost two years now.

As far as I can tell, this is not a Strapi issue...

**Comment by ogrotten** [comment]
The node-gyp issue is not. However, the ticket is about strapi automated install of a db adapter that fails. In other words, when trying to use a feature of the app (set up mongodb), the feature is unusable. 

I'm not suggesting that you fix the node-gyp problem. I'm suggesting that there may be some solution to get the adapter to install appropriately for strapi's purposes.

**Comment by loicsaintroch** [comment]
I'm not sure to understand what you want. There is no way for us to override the npm installation if that what you mean.

**Comment by ogrotten** [comment]
Not necessarily override, but i'm suggesting that perhaps there's another solution... something like load your own working install of the failing lib, or install a precompiled binary, or use even an altogether different solution for the same function.

I obviously am just a guy using your app so am not privvy to the details, but what I'm suggesting is that there may a way to make strapi work past this particular problem in a way that isn't immediatly obvious. Because, whatever the reason and unless I missed something, strapi currently isn't useful with mongodb.

**Comment by loicsaintroch** [comment]
I honestly don't know what to answer to this issue except that this is not an issue on our side but from the `sails-mongo` adapter. I know @tjwebb is working hard on Waterline and the migration of adapters from Sails to Waterline so he might have a solution about this.

On our side, I can't think of a magical solution...

**Comment by loicsaintroch** [comment]
Hi @perminder-klair. Unfortunately, this is not an issue on our side but an issue with the `sails-mongo` node module. There is nothing we can do here... Sorry.
