### ISSUE TITLE
Make documentation searchable

### ISSUE THREAD

**Issue by jakobrosenberg** [wistityhq/strapi#70]
Love the documentation, but I wish there was a way to search it.

**Comment by sylvainlap** [comment]
The possibility to have a one-page doc would be great !

**Comment by loicsaintroch** [comment]
Hey @jakobrosenberg and @sylvainlap. I have some good news for you: the documentation for the v2 will be searchable and a one-page documentation will also be available! Thank you for your feedback we appreciate your help. ;-)
