### ISSUE TITLE
Should I worry about my code getting overwritten Studio?

### ISSUE THREAD

**Issue by jakobrosenberg** [wistityhq/strapi#72]
Would it be possible to add comments to generated files that show which parts Studio will overwrite?

**Comment by Aurelsicoko** [comment]
The Studio only overrides the model file (ex: Article.settings.json) and generate new API folder.

**Comment by loicsaintroch** [comment]
No you don't need to worry about your code being overridden by the Studio. As @Aurelsicoko said the Studio only write your JSON models and config files with the default controllers. You can update your controllers as much as you want-- the Studio will never update them.
