### ISSUE TITLE
Graphql queries work incorrect

### ISSUE THREAD

**Issue by kulakowka** [wistityhq/strapi#73]
It seems graphql does not work properly.

Here is a list of articles in the my admin page:

<img width="995" alt="2016-01-31 17 47 19" src="https://cloud.githubusercontent.com/assets/557190/12702763/c30d64ec-c842-11e5-8c5b-819d06fe62c4.png">

When I'm trying to get a list of articles, author of the article is not included in all articles. 

<img width="613" alt="2016-01-31 17 51 55" src="https://cloud.githubusercontent.com/assets/557190/12702784/5df49ab6-c843-11e5-914c-eb3763479dff.png">

The parameter `createdBy` is only for the first article. As far as I know it's not proper behavior for graphql. Maybe it's a bug?

My strapi version:
```
» strapi -v
1.5.4
```

**Comment by kulakowka** [comment]
I noticed a very strange behavior. Sometimes it works correctly. Sometimes not. I was unable to understand the reason.

**Comment by Aurelsicoko** [comment]
Which Waterline adapter are you using? I think the problem comes from Waterline... Sometimes it seems the values are not populated in the response object.

**Comment by kulakowka** [comment]
@Aurelsicoko i'm using `sails-mongo`, but there is a possibility that it is buggy at the default settings.

I will try to create a new application, without any additional adapters. I'll let you know about the results here.

**Comment by kulakowka** [comment]
I tested it on a new application. Here's what happens:

Standard API gives data correctly.

[http://localhost:1337/article](http://localhost:1337/article)

```json
[  
   {  
      "contributors":[  
         {  
            "username":"kulakowka",
            "email":"kulakowka@gmail.com",
            "lang":"en_US",
            "template":"default",
            "id_ref":"1",
            "provider":"local",
            "id":1,
            "createdAt":"2016-01-31T23:19:54.227Z",
            "updatedAt":"2016-01-31T23:19:54.237Z"
         }
      ],
      "comments":[  
         {  
            "content":"Comment 1 for article 1",
            "lang":"en_US",
            "template":"default",
            "createdBy":1,
            "updatedBy":1,
            "article":1,
            "id":1,
            "createdAt":"2016-01-31T23:21:16.614Z",
            "updatedAt":"2016-01-31T23:21:29.139Z"
         },
         {  
            "content":"Comment 2 for article 1",
            "lang":"en_US",
            "template":"default",
            "createdBy":1,
            "updatedBy":1,
            "article":1,
            "id":2,
            "createdAt":"2016-01-31T23:21:31.371Z",
            "updatedAt":"2016-01-31T23:21:39.347Z"
         }
      ],
      "createdBy":{  
         "username":"kulakowka",
         "email":"kulakowka@gmail.com",
         "lang":"en_US",
         "template":"default",
         "id_ref":"1",
         "provider":"local",
         "id":1,
         "createdAt":"2016-01-31T23:19:54.227Z",
         "updatedAt":"2016-01-31T23:19:54.237Z"
      },
      "updatedBy":{  
         "username":"kulakowka",
         "email":"kulakowka@gmail.com",
         "lang":"en_US",
         "template":"default",
         "id_ref":"1",
         "provider":"local",
         "id":1,
         "createdAt":"2016-01-31T23:19:54.227Z",
         "updatedAt":"2016-01-31T23:19:54.237Z"
      },
      "title":"Article 1",
      "content":"Test for article 1",
      "lang":"en_US",
      "template":"default",
      "id":1,
      "createdAt":"2016-01-31T23:19:59.536Z",
      "updatedAt":"2016-01-31T23:20:10.032Z"
   },
   {  
      "contributors":[  
         {  
            "username":"kulakowka",
            "email":"kulakowka@gmail.com",
            "lang":"en_US",
            "template":"default",
            "id_ref":"1",
            "provider":"local",
            "id":1,
            "createdAt":"2016-01-31T23:19:54.227Z",
            "updatedAt":"2016-01-31T23:19:54.237Z"
         }
      ],
      "comments":[  
         {  
            "content":"Comment 1 for article 2",
            "lang":"en_US",
            "template":"default",
            "createdBy":1,
            "updatedBy":1,
            "article":2,
            "id":3,
            "createdAt":"2016-01-31T23:21:41.160Z",
            "updatedAt":"2016-01-31T23:21:52.418Z"
         },
         {  
            "content":"Comment 2 for article 2",
            "lang":"en_US",
            "template":"default",
            "createdBy":1,
            "updatedBy":1,
            "article":2,
            "id":4,
            "createdAt":"2016-01-31T23:21:54.028Z",
            "updatedAt":"2016-01-31T23:22:03.647Z"
         }
      ],
      "createdBy":{  
         "username":"kulakowka",
         "email":"kulakowka@gmail.com",
         "lang":"en_US",
         "template":"default",
         "id_ref":"1",
         "provider":"local",
         "id":1,
         "createdAt":"2016-01-31T23:19:54.227Z",
         "updatedAt":"2016-01-31T23:19:54.237Z"
      },
      "updatedBy":{  
         "username":"kulakowka",
         "email":"kulakowka@gmail.com",
         "lang":"en_US",
         "template":"default",
         "id_ref":"1",
         "provider":"local",
         "id":1,
         "createdAt":"2016-01-31T23:19:54.227Z",
         "updatedAt":"2016-01-31T23:19:54.237Z"
      },
      "title":"Article 2",
      "content":"Text for article 2",
      "lang":"en_US",
      "template":"default",
      "id":2,
      "createdAt":"2016-01-31T23:20:11.033Z",
      "updatedAt":"2016-01-31T23:20:19.405Z"
   }
]
```

But graphql response has wrong data:

[http://localhost:1337/graphql?query={articles{id,title,createdBy{id,username},comments{id,content}}}](http://localhost:1337/graphql?query={articles{id,title,createdBy{id,username},comments{id,content}}})

```json
{  
   "data":{  
      "articles":[  
         {  
            "id":"1",
            "title":"Article 1",
            "createdBy":{  
               "id":"1",
               "username":"kulakowka"
            },
            "comments":[  
               {  
                  "id":"1",
                  "content":"Comment 1 for article 1"
               },
               {  
                  "id":"2",
                  "content":"Comment 2 for article 1"
               },
               {  
                  "id":"3",
                  "content":"Comment 1 for article 2"
               },
               {  
                  "id":"4",
                  "content":"Comment 2 for article 2"
               }
            ]
         },
         {  
            "id":"2",
            "title":"Article 2",
            "createdBy":null,
            "comments":[  
               {  
                  "id":"1",
                  "content":"Comment 1 for article 1"
               },
               {  
                  "id":"2",
                  "content":"Comment 2 for article 1"
               },
               {  
                  "id":"3",
                  "content":"Comment 1 for article 2"
               },
               {  
                  "id":"4",
                  "content":"Comment 2 for article 2"
               }
            ]
         }
      ]
   }
}
```

I did not make any settings other than the relationship between the models.

Maybe I'm wrong to set up a relationship between the models?

![2016-02-01 2 32 22](https://cloud.githubusercontent.com/assets/557190/12705974/0f3ed7da-c88c-11e5-9d71-8711f9b5f5d9.png)

![2016-02-01 2 33 49](https://cloud.githubusercontent.com/assets/557190/12705997/44c36ba0-c88c-11e5-8d1b-6ccef580e044.png)

**Comment by Aurelsicoko** [comment]
No, your relationships look good. I will take a look at it tomorrow, there is an issue but it's strange because we didn't notice this before. The GraphQL support has not been updated since 2 months.

**Comment by kulakowka** [comment]
I found something strange. Take a look at the screenshot:

![2](https://cloud.githubusercontent.com/assets/557190/12706185/57fdac9a-c890-11e5-97d4-6422c985d7f4.png)

![1](https://cloud.githubusercontent.com/assets/557190/12706186/581201e0-c890-11e5-8f24-bcbab372ea9b.png)

I do not know whether it is right or not. But it looks strange.

Perhaps this is a bug in the admin panel? 

When I switch on the fields Relations

![2016-02-01 3 06 34](https://cloud.githubusercontent.com/assets/557190/12706212/d50dd912-c890-11e5-8b0b-def08e677546.png)

Preview looks like this

![2016-02-01 3 07 20](https://cloud.githubusercontent.com/assets/557190/12706217/ee98485e-c890-11e5-8b68-721e417afefa.png)

Then I switch to a different field

![2016-02-01 3 07 59](https://cloud.githubusercontent.com/assets/557190/12706225/047aa676-c891-11e5-9f96-f12ea0c943ce.png)

Preview looks like this

![2016-02-01 3 08 42](https://cloud.githubusercontent.com/assets/557190/12706233/209ce134-c891-11e5-8f29-9101a7f919ed.png)

Nothing but the name does not change.  Although it is obvious that the scheme should be changed.

**Comment by Aurelsicoko** [comment]
[Fixed](https://github.com/wistityhq/waterline-graphql/commit/21b4ab3715374f0ba8104bf74df99bdd8b1a3b07)! I had the same behavior. Thanks for your detailed feedback.

**Comment by kulakowka** [comment]
I'm glad to help you.
