### ISSUE TITLE
How to change permanent DB for User model? 

### ISSUE THREAD

**Issue by kulakowka** [wistityhq/strapi#75]
How to change `Permanent DB` for `User`, `Role`, `Permission` models? I can not find it in the documentation. I would be grateful if you tell me where to look.

**Comment by kulakowka** [comment]
I think I understand.

I have edited the `connection` settings of models:
`/api/user/models/User.settings.json`
```json
{
  "identity": "user",
  "connection": "mongodb_main",
  ...
}
```

The same thing I've done for other models `Role`, `Route`, `Email` etc... 

It seems to work. I did everything right?

**Comment by loicsaintroch** [comment]
Yes you did! ;-)

**Comment by kulakowka** [comment]
@loicsaintroch cool! Thank you for quick reply. :thumbsup: :beer:
