### ISSUE TITLE
Add example validations to documentation

### ISSUE THREAD

**Issue by kulakowka** [wistityhq/strapi#76]
I could not figure out how to add [these validation](http://strapi.io/documentation/models#validations) to the model. I understood only when I read the documentation to the [waterline](https://github.com/balderdashy/waterline#validations). 

I changed the `type` attribute to `alpha`. Now, validation work the as I wanted.

```json
...
"attributes": {
    "username": {
      "minLength": 3,
      "required": true,
      "primaryKey": true,
      "type": "alpha",
      "unique": true
    },
    ...
}
...
```
Maybe it makes sense to add examples of such validations to the documentation page?

**Comment by loicsaintroch** [comment]
Hey @kulakowka. Thank you very much for your suggestion regarding the documentation we appreciate your help. We added some examples for the v2.0.0 docs about model validations. We'll release it soon. :-)
