### ISSUE TITLE
How to change user route to /user/:username? 

### ISSUE THREAD

**Issue by kulakowka** [wistityhq/strapi#78]
I would like to change the route for user from `/user/:id` to `/user/:username`. How can I do it? 
Can I do this with waterline? 
Or do I have to write custom action in the user controller?

I'm confused :) probably time for me to go to bed and try to do it tomorrow :)

**Comment by sylvainlap** [comment]
You cannot do this natively with Waterline (moreover Waterline will be removed in v2).

You have to write a new controller in /api/user/controllers/User.js, and add this new route in /api/users/config/routes.json (or update the /user/:id one).

Somthing like:

```
findByUsername: function * () {
    try {
      const user = yield User.find({ username: this.params.username });

      if (_.isEmpty(user)) {
        this.status = 404;
      } else {
        this.body = user;
      }
    } catch (err) {
      this.body = err;
    }
  },
```

**Comment by kulakowka** [comment]
Thank you. That's exactly what I did.
