### ISSUE TITLE
Cannot connect to dashboard.

### ISSUE THREAD

**Issue by ogrotten** [wistityhq/strapi#8]
url: http://studio.strapi.io/#!/login

Given proper info, the login doesn't continue to the dashboard. the progress bar across the top advances, but the page doesn't react to the form submission.

I tried 'forgot password' just in case I had it wrong (not likely) and the forgot password screen behaves the same way.

**Comment by Aurelsicoko** [comment]
We worked on the Strapi Studio the whole day. Maybe we broke something. We will investigate asap ;)

**Comment by loicsaintroch** [comment]
Yes we definitely broke the Studio URLs because of some DNS changes... I just reestablished the `http://dashboard.strapi.io`. It will be effective in less than 20 minutes by now.

As you may know, this feature will now be called `Studio`.
