### ISSUE TITLE
How to select where in array?

### ISSUE THREAD

**Issue by kulakowka** [wistityhq/strapi#83]
I want to select all Articles where i'm contributor. How i can do this? 

In mongoose a can do it like this:
```
Article.find({contributors: [userId])
```

But i can't understand how to make it with blueprint api.

I tried to make it so:
```
GET /article?where={"contributors": ["123"]}
```
But it did not work. Do you have any ideas?

P.S. Please forgive me if the question will seem silly. I almost made a backend for my new project. But I can not deal with this request.

**Comment by pierreburgy** [comment]
Hi @kulakowka , could you try `GET /user/:youUserId?populate=articles`

**Comment by kulakowka** [comment]
@pierreburgy That's not what I need. I want to specify a limit, sorting and so on. If I pick up the article with a population, I can not specify how many items to load. Also I can not specify which fields in the article should be populated. What if the user will be 1,000 articles, and I need only 10 per page.

**Comment by Aurelsicoko** [comment]
@kulakowka: Your request is impossible on the current version of Strapi. You should create a new endpoint like `GET /article/:relation/:relationId` and add to your controller something like this:

`
// In your Article.js controller
findRelation: function * () {
  this.model = model;
  try {
    this.request.query.where = {};
    this.request.query.where[this.params.relation] = this.params.relationId;
    this.body = yield strapi.hooks.blueprints.find(this);
  } catch (err) {
    this.body = err;
  }
}
`
