### ISSUE TITLE
Protect GraphQL route like the other endpoints?

### ISSUE THREAD

**Issue by zth** [wistityhq/strapi#84]
Hi!

First of all, I found strapi a few days ago and I'm really amazed by what you've managed to accomplish so far. I got up and running super quick, and the built-in GraphQL support is just great. Kudos, really! I look forward to following this project and I plan on using it for several protoypes and implementations already. 

Anyway, my question is about the GraphQL route - can this be protected with policies/permissions just like other routes? How would one go about doing that?

Thanks for all your work!

**Comment by Aurelsicoko** [comment]
@zth: Thanks for your kind words and support! Currently, you can't protect the GraphQL query with policies and permissions. No one already did that during the development of this feature a few months ago. We already thought about that but it's not our priority for now.

We're adding JSON API support which allows doing the same things as GraphQL to select specific fields in your request. If you have time to submit a PR to support this feature, we'll be glad to help you doing that!

**Comment by loicsaintroch** [comment]
Hey @zth, thanks a lot for your suggestion. @Aurelsicoko worked on this suggestion for the past few days and the feature will be released for the v2.0.0. :-)
