### ISSUE TITLE
npm install is returning shasum check fail on mac os x

### ISSUE THREAD

**Issue by nitetrik** [wistityhq/strapi#85]
When i install Strapi thru NPM on Mac os X Yosemite, i get shasum check fail for a certain dependency.

**Comment by loicsaintroch** [comment]
Is it related to #59 and #67 ?

npm >= v3.0.0 no longer supports symbolic links in the `node_modules` directory. We'll work on a speedier solution to optimize `$ strapi new` that will be released in the v2. But in the mean time, your new Strapi app's dependencies must be set up using the classic `$ npm install` process.

**Comment by nitetrik** [comment]
Um not quite, its when initially installing strapi "npm install -g strapi". I can install strapi via npm fine on linux, but on mac os x it doesnt even install it fails with a certain package that looks like a dependency. when i get home will paste the output error.

**Comment by loicsaintroch** [comment]
Did you try using `sudo`? Like `sudo npm install strapi -g`?

**Comment by nitetrik** [comment]
I havent tried `sudo`, will try that and let you know, thanks

**Comment by nitetrik** [comment]
I fixed it by updating node to latest version on my local development machine to 5.6.0.  it installed without a problem. It was a weird issue.
