### ISSUE TITLE
Feature request - email password and config file

### ISSUE THREAD

**Issue by k20human** [wistityhq/strapi#88]
Hi,

I just discover your framework (and I like it :+1: ), I used SailsJS for my project before like you and I have same problematics

I have two requests :
- Isit possible to give us the possibility to add a config file with environement specific varaibles? For in exemple in Sails i had a config file in config/ folder (named myconf.js) with a content like this :
```
module.exports.myconf = {
	SHAREPOINT: false,
	UPLOAD_PATH: 'assets/files/',
	UPLOAD_TMP_PATH: '.tmp/public/files/',
	ALLOWED_TYPES: ['image/jpeg', 'image/png', 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],
};
``` 
and in my application i can use this variables like this `sails.config.myconf.ALLOWED_TYPES` it's very usefull.
- You store email password in a file `smtp.json` per environment. But if we commit these files we expose our password! I think it might be a good idea to externalize password in a file that will be in .gitignore

**Comment by loicsaintroch** [comment]
Hey @k20human,

Yes it is possible to have a file like you wrote in a specific environment. Strapi (like Sails) build a dictionary based on your files and directories. `strapi.config` is build when the application loads and register everything from the `./config` directory. For example the file you wrote in your issue will be accessible at `strapi.config.myconf` and the `myconf` value changes depending on the environment.

I agree. We'll improve the `.gitignore` file for v2.

**Comment by k20human** [comment]
Hi @loicsaintroch thank you ! I close the issue and wait for v2 :)

**Comment by loicsaintroch** [comment]
I actually want to leave it open since the v2 is not released yet. It's much easier to see what's left for this release.

**Comment by k20human** [comment]
Ok. I think you can apply same thing for database password file (databases.json)

**Comment by loicsaintroch** [comment]
Definitely yes!

**Comment by loicsaintroch** [comment]
This is now fixed and will be released for the v2. We simply ignore every `production` directory.
