### ISSUE TITLE
The dashboard url is not in the documentation.

### ISSUE THREAD

**Issue by ogrotten** [wistityhq/strapi#9]
As a matter of fact, according to Google, the word *studio* does not appear on strapi.io when searching using the term *site:strapi.io studio*.

**Comment by Aurelsicoko** [comment]
We are improving the documentation to help users to understand as much as possible our ecosystem. The "Strapi Studio" is on the list of the stuff to improve. Thank you for your feedback!

**Comment by loicsaintroch** [comment]
As a matter of facts, we spend a lot of time today improving the documentation on *why* you need the Strapi Studio and *how* you can use it.

It will be published soon!
