### ISSUE TITLE
Can't get the cron feature to work

### ISSUE THREAD

**Issue by discordance** [wistityhq/strapi#91]
Hello. Just tried to test some dummy functions with ./config/functions/cron.js.

Eg:
```  
// function that should fire every minute
'* */1 * * * *': function () {
    strapi.log.info('test');
  }
```

except a first log, nothing fire then

**Comment by discordance** [comment]
Is there any workaround ? or the cron syntax doesn't apply in the same way ?

**Comment by loicsaintroch** [comment]
Hey @discordance. I just tested and it woks fine without the optional second info:

```js
// function that should fire every minute
'* */1 * * * *': function () {
  strapi.log.info('test');
}
```
