### ISSUE TITLE
Changing API path breaks the admin panel.

### ISSUE THREAD

**Issue by JordanMajd** [wistityhq/strapi#93]
Using Strapi Studio there is an option to change your API endpoint, I changed it from empty to `/api`.

This breaks the admin panel. When I try to access it at `/admin` I get a 404 for 2 resources:

- `GET /admin/config`
- `POST /auth/logout`

I know this is a simple fix on my end by changing the but is there a way that this could be automated?

To reproduce:

1. create a new app using `strapi new testapp`
1. start the app `strapi start`
1. set up the config key for strapi studio.
1. open up strapi studio for app set `config -> general -> prefix api` to `/api`
1. restart the server and open the admin panel at `localhost:1337/admin/`

**Comment by loicsaintroch** [comment]
Is it related to #68? If so, can you please try the give solution and give us a feedback. If not, we'll take a look at it.

**Comment by JordanMajd** [comment]
Thanks for the quick response,

Sorry, I must not have searched the issues hard enough before posting this one.

That is definitely the same problem. I haven't tried the solution yet, but that will definitely fix the issue.

Closing.
