### ISSUE TITLE
Studio down ?

### ISSUE THREAD

**Issue by Charl---** [wistityhq/strapi#94]
The studio seems to be offline.

**Comment by pierreburgy** [comment]
Hi @Charl--- , we fixed the issue. Could you try again and let us know please?

**Comment by Charl---** [comment]
hi @pierreburgy, 
Thanks for the quick answer.

The studio seems to be ok, but i was unable to sync, so i logout using the CLI and now it is impossible to login.

when i try to login using
`strapi login`

i gave email and pass and got this error 

`/home/charl/.nvm/versions/node/v5.3.0/lib/node_modules/strapi/bin/strapi-login.js:118
              email: body.user.email,
                              ^
TypeError: Cannot read property 'email' of undefined
    at /home/charl/.nvm/versions/node/v5.3.0/lib/node_modules/strapi/bin/strapi-login.js:118:31
    at FSReqWrap.oncomplete (fs.js:82:15)`

**Comment by pierreburgy** [comment]
Thanks for you answer, we are working on the issue. It should be working again in a few moments.

**Comment by pierreburgy** [comment]
Problem fixed. Is it working now from you machine?

**Comment by dustinaevans** [comment]
Seems that the studio login page is still broken?

**Comment by Charl---** [comment]
Everything work fine thank you very much @pierreburgy

**Comment by pierreburgy** [comment]
Great. You're welcome, sorry for the inconvenience.
