### ISSUE TITLE
Koa middleware?

### ISSUE THREAD

**Issue by kokujin** [wistityhq/strapi#95]
Nice project! I plan to document my API using this Koa middleware, [koa-docs](https://github.com/a-s-o/koa-docs).

How do I go about this using Strapi? Is there any documentation on using third party middleware somewhere? Thanks

**Comment by loicsaintroch** [comment]
Hey @kokujin, that's a very good question-- love it! It will be possible to use Koa middlewares thanks to custom hooks which will be available (and documented of course) when we'll release the v2 in the next few weeks. Thanks for your feed we appreciate. :-)
